from django.urls import path
from . import views


urlpatterns = [
  path(
    '',
    views.home,
    name='home'
  ),
  path(
    'about/', 
    views.about,
    name='about'
  ),
  path(
    'blogs/', 
    views.blogs,
    name='blogs'
  ),
  path(
    'contact/', 
    views.contact,
    name='contact'
  ),
  path(
    'register/', 
    views.registerView,
    name='register'
  ),
  path(
    'login/', 
    views.loginView,
    name='login'
  ),
  path(
    'logout/', 
    views.logout_view,
    name='logout'
  ),
  path(
    'subscribe/',
    views.subscribe,
    name='subscribe'
  ),
  path(
    'send-newsletter/',
    views.send_newsletter,
    name='send_newsletter'
  ),
  path(
    'password_reset/',
    views.password_reset_view,
    name='password_reset'
  ),
  path(
    'password_reset/done/',
    views.password_reset_done_view,
    name='password_reset_done'
  ),
  # <uidb64> below:
  path(
    'reset/<int:pk>/<str:token>/',
    views.password_reset_confirm_view,
    name='password_reset_confirm'
  ),
  path(
    'password_reset/complete/',
    views.password_reset_complete_view,
    name='password_reset_complete'
  ),
  path(
    'screens/', 
    views.screens,
    name='homeScreens'
  ),
]