# Generated by Django 6.0.2 on 2026-03-01 11:30

import store.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Female_wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MW', 'Male Wear'), ('FW', 'Female Wear'), ('AC', 'Accessories'), ('MS', 'Men Singlets'), ('MB', 'Men Boxers'), ('MP', 'Men Pants'), ('FS', 'Female Singlets'), ('FP', 'Female Pants'), ('FB', 'Female Boxers'), ('FB', 'Female Bras'), ('FS', 'Female Skirts'), ('FT', 'Female Tights'), ('OT', 'Other')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts', validators=[store.validators.validationRules])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Male_wear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MW', 'Male Wear'), ('FW', 'Female Wear'), ('AC', 'Accessories'), ('MS', 'Men Singlets'), ('MB', 'Men Boxers'), ('MP', 'Men Pants'), ('FS', 'Female Singlets'), ('FP', 'Female Pants'), ('FB', 'Female Boxers'), ('FB', 'Female Bras'), ('FS', 'Female Skirts'), ('FT', 'Female Tights'), ('OT', 'Other')], max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stats', validators=[store.validators.validationRules])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MW', 'Male Wear'), ('FW', 'Female Wear'), ('AC', 'Accessories'), ('MS', 'Men Singlets'), ('MB', 'Men Boxers'), ('MP', 'Men Pants'), ('FS', 'Female Singlets'), ('FP', 'Female Pants'), ('FB', 'Female Boxers'), ('FB', 'Female Bras'), ('FS', 'Female Skirts'), ('FT', 'Female Tights'), ('OT', 'Other')], max_length=2)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_image', models.ImageField(upload_to='upload', validators=[store.validators.validationRules])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('discount', models.FloatField(default=0.0)),
                ('desc', models.TextField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puschase_id', models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
