# Generated by Django 6.0.6 on 2026-09-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='hex_code',
        ),
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.AddField(
            model_name='color',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants_color', to='shop.products'),
        ),
        migrations.AddField(
            model_name='color',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants_images', to='shop.products'),
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants_size', to='shop.products'),
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
