# Generated by Django 6.0.6 on 2026-09-18 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_color_productvariant_productimage_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
    ]
