# Generated by Django 6.0.6 on 2026-09-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, through='shop.CartItem', to='shop.products'),
        ),
    ]
