# Generated by Django 6.0.6 on 2026-09-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
